import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { TABLE_KINDS } from '@/server/db/table-names';

/**
 * `infra/tables.json` is generated by `npm run db:create`, and it is the thing
 * a cloud deploy hands to CloudFormation. Nothing else in the suite looks at
 * it, so a mistake there is invisible until a stack fails at 2am.
 */
const template = JSON.parse(readFileSync(resolve('infra/tables.json'), 'utf8')) as {
  Parameters: Record<string, { AllowedValues?: string[] }>;
  Resources: Record<string, { Type: string; Properties: Record<string, unknown> }>;
  Outputs: Record<string, unknown>;
};

/** What DynamoDB actually accepts as a table name. */
const LEGAL_TABLE_NAME = /^[A-Za-z0-9_.-]{3,255}$/;

describe('the CloudFormation template for the five tables', () => {
  it('declares exactly the five tables and no sixth', () => {
    const tables = Object.values(template.Resources).filter(
      (resource) => resource.Type === 'AWS::DynamoDB::Table',
    );
    expect(tables).toHaveLength(TABLE_KINDS.length);
    expect(Object.keys(template.Outputs)).toHaveLength(TABLE_KINDS.length);
  });

  it('substitutes the environment into the table name', () => {
    // The bug this guards: emitted as a bare string, `${Env}` is never
    // substituted, and CloudFormation asks DynamoDB for a table whose name
    // contains `$`, `{` and `}`. The stack fails on create.
    for (const [id, resource] of Object.entries(template.Resources)) {
      const name = resource.Properties.TableName;
      expect(name, `${id} must use Fn::Sub`).toEqual({
        'Fn::Sub': expect.stringContaining('${Env}'),
      });
    }
  });

  it('produces a legal table name for every environment it allows', () => {
    const environments = template.Parameters.Env?.AllowedValues ?? [];
    expect(environments.length).toBeGreaterThan(0);

    for (const resource of Object.values(template.Resources)) {
      const pattern = (resource.Properties.TableName as { 'Fn::Sub': string })['Fn::Sub'];
      for (const env of environments) {
        const resolved = pattern.replace('${Env}', env);
        expect(resolved, `${resolved} is not a legal DynamoDB table name`).toMatch(
          LEGAL_TABLE_NAME,
        );
      }
    }
  });

  it('keeps the protections that make a production table survivable', () => {
    for (const [id, resource] of Object.entries(template.Resources)) {
      expect(resource.Properties.DeletionProtectionEnabled, id).toBe(true);
      expect(resource.Properties.PointInTimeRecoverySpecification, id).toEqual({
        PointInTimeRecoveryEnabled: true,
      });
      expect(resource.Properties.SSESpecification, id).toEqual({ SSEEnabled: true });
    }
  });

  it('carries the two indexes the transaction queries depend on', () => {
    const transactions = template.Resources.TransactionsTable;
    const indexes = (transactions?.Properties.GlobalSecondaryIndexes ?? []) as Array<{
      IndexName: string;
    }>;
    expect(indexes.map((index) => index.IndexName).sort()).toEqual(['gsi1', 'gsi2']);
  });
});
